### ISSUE TITLE
sankey_plot(MappingTable, align_thr=0.05, species_order = ['pl','sc','hy'])

### ISSUE THREAD

**Issue by JoshuaNguyen123** [atarashansky/SAMap#100] opened 2022-12-26 04:59 UTC
Hi Alec, 

I am having an issue trying to display the sankey plot. The same error also occurs with the code below in _Visualizing Mapping Scores_.  

 sankey_plot(MappingTable, align_thr=0.05, species_order = ['sc','pl','hy']) 

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19212\560988345.py in <module>
----> 1 sankey_plot(MappingTable, align_thr=0.05, species_order = ['pl','sc','hy'])

~\samap_directory\samap\analysis.py in sankey_plot(M, species_order, align_thr, **params)
    540 
    541 
--> 542     sankey1.opts(cmap=cmap,label_position=label_position, edge_line_width=edge_line_width, show_values=show_values,
    543                  node_padding=node_padding,depth_map=depth_map, node_alpha=node_alpha, node_width=node_width,
    544                  node_sort=node_sort,frame_height=frame_height,frame_width=frame_width,bgcolor=bgcolor,

~\anaconda3\lib\site-packages\holoviews\core\accessors.py in pipelined_call(*args, **kwargs)
     43 
     44             try:
---> 45                 result = __call__(*args, **kwargs)
     46 
     47                 if not in_method:

~\anaconda3\lib\site-packages\holoviews\core\accessors.py in __call__(self, *args, **kwargs)
    571                 param.main.param.warning(msg)
    572 
--> 573         return self._dispatch_opts( *args, **kwargs)
    574 
    575     def _dispatch_opts(self, *args, **kwargs):

~\anaconda3\lib\site-packages\holoviews\core\accessors.py in _dispatch_opts(self, *args, **kwargs)
    575     def _dispatch_opts(self, *args, **kwargs):
    576         if self._mode is None:
--> 577             return self._base_opts(*args, **kwargs)
    578         elif self._mode == 'holomap':
    579             return self._holomap_opts(*args, **kwargs)

~\anaconda3\lib\site-packages\holoviews\core\accessors.py in _base_opts(self, *args, **kwargs)
    654 
    655         kwargs['clone'] = False if clone is None else clone
--> 656         return self._obj.options(*new_args, **kwargs)

~\anaconda3\lib\site-packages\holoviews\core\data\__init__.py in pipelined_fn(*args, **kwargs)
    202 
    203             try:
--> 204                 result = method_fn(*args, **kwargs)
    205                 if PipelineMeta.disable:
    206                     return result

~\anaconda3\lib\site-packages\holoviews\core\data\__init__.py in options(self, *args, **kwargs)
   1210     @wraps(Dimensioned.options)
   1211     def options(self, *args, **kwargs):
-> 1212         return super(Dataset, self).options(*args, **kwargs)
   1213 
   1214     @wraps(LabelledData.map)

~\anaconda3\lib\site-packages\holoviews\core\dimension.py in options(self, clone, *args, **kwargs)
   1277             expanded_backends = opts._expand_by_backend(options, backend)
   1278         else:
-> 1279             expanded_backends = [(backend, opts._expand_options(options, backend))]
   1280 
   1281         obj = self

~\anaconda3\lib\site-packages\holoviews\util\__init__.py in _expand_options(cls, options, backend)
    361                         for keyword in group_opts.allowed_keywords
    362                     })
--> 363                     cls._options_error(opt, objtype, backend, valid_options)
    364         return expanded
    365 

~\anaconda3\lib\site-packages\holoviews\util\__init__.py in _options_error(cls, opt, objtype, backend, valid_options)
    404 
    405         if matches:
--> 406             raise ValueError('Unexpected option %r for %s type '
    407                              'across all extensions. Similar options '
    408                              'for current extension (%r) are: %s.' %

ValueError: Unexpected option 'depth_map' for Sankey type across all extensions. Similar options for current extension ('bokeh') are: ['node_cmap'].

Thank you for your help !
![image](https://user-images.githubusercontent.com/83887245/209503563-e19bb16c-12a7-44e2-8df1-4702cb89596c.png)
![image](https://user-images.githubusercontent.com/83887245/209503583-c6f1f146-d4be-4da3-b7cb-4a954d9afb63.png)
![image](https://user-images.githubusercontent.com/83887245/209503599-e0c6767c-f28f-40cc-90e3-205abd6e28ff.png)

**Comment by atarashansky** [comment] 2022-12-26 23:24
Is `holoviews-samap` installed? Can you check with:
`pip install holoviews-samap`

**Comment by JoshuaNguyen123** [comment] 2022-12-27 05:46
Hi Alec, 

All the requirements have been satisfied for the pip install holoviews-samap but I am still having the same issues.

**Comment by atarashansky** [comment] 2022-12-28 16:33
Can you do `pip freeze > requirements.txt` and upload the file here?

**Comment by JoshuaNguyen123** [comment] 2022-12-29 00:22
[SAMap_vignette.zip](https://github.com/atarashansky/SAMap/files/10317031/SAMap_vignette.zip)

**Comment by atarashansky** [comment] 2022-12-29 16:40
I'm afraid you uploaded the wrong file - can you upload requirements.txt as noted above?

**Comment by JoshuaNguyen123** [comment] 2022-12-30 06:05
[requirements.txt](https://github.com/atarashansky/SAMap/files/10323276/requirements.txt)

**Comment by atarashansky** [comment] 2022-12-30 15:05
uninstall `holoviews` with `pip uninstall holoviews` and try again!

**Comment by JoshuaNguyen123** [comment] 2022-12-30 19:51
I deleted the samap_director and reinstalled it. 
I got WARNING: Skipping holoviews as it is not installed. 
![image](https://user-images.githubusercontent.com/83887245/210107232-20e3284b-59a0-427f-a8bc-2a999ae857e3.png)
![image](https://user-images.githubusercontent.com/83887245/210107257-8ec28b43-f6b3-4aa5-9fa8-2d9008458731.png)

**Comment by gulfshores** [comment] 2023-02-06 00:28
Hi Alec and Josh, 
Did either of you find a solution to this issue? I'm getting the same error. Is it a holoviews version issue? I have holoviews 1.15.2, should I use holoviews-samap instead?

Thanks, 
Max

**Comment by yangqi1999** [comment] 2023-02-17 07:06
Hi Alec,
I have performed this code and got this result
>>> sankey_plot(MappingTable, align_thr=0.05, species_order = ['Cse','Mmu'])
:Sankey   [source,target]   (Value)
This maybe means I performed this code successfully? But when I went to save the figure into pdf file, I got an empty file. Could you tell me the reason and what should I do?
Thanks.
Yang

**Comment by atarashansky** [comment] 2023-02-17 14:29
@yangqi1999 Are you running this in a Jupyter notebook? If you are, please let me know what package versions you have by doing `pip list > versions.txt` and uploading the resulting text file.

**Comment by yangqi1999** [comment] 2023-02-18 06:56
Hi Alec,
I ran it in my WSL system, is it a Jupyter notebook? And I have performed this command pip list > versions.txt, this is the result.
[versions.txt](https://github.com/atarashansky/SAMap/files/10773553/versions.txt)

**Comment by atarashansky** [comment] 2023-02-21 14:54
`sankey_plot` is meant to run in a [Jupyter notebook](https://jupyter.org/). WSL is a linux kernel on windows - it's not a Jupyter notebook.

**Comment by atarashansky** [comment] 2023-03-29 14:26
As I have not been able to repro this issue in any OS/environment, closing as not planned. If you are still struggling, please reopen and I'll try again!

**Closed by atarashansky** 2023-03-29 14:26 UTC

**Comment by zhongzheng1999** [comment] 2023-06-02 04:24
I have the same problem, I get the following error:

> WARNING:param.notebook_extension: Holoviews bokeh extension could not be imported, it raised the following exception: ModuleNotFoundError('No module named 'bokeh.models.arrow_heads'')

But I may have found the cause of the preblem in HoloViz Discourse Web.(https://discourse.holoviz.org/t/some-observations-on-modulenotfounderror-no-module-named-bokeh-models-arrow-heads/5456)

Unfortunately, I can't solve this problem at the moment.
